version: "3"

services:
  jupyter:
    image: "jupyter/base-notebook"
    volumes:
      - ./:/home/jovyan/work
      - ./configure_environment.sh:/usr/local/bin/before-notebook.d/configure_environment.sh
    ports:
      - 8888:8888
    environment:
      - REDCAP_TOKEN=${REDCAP_TOKEN}
